# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b559683573eb4e083d55d92d6c8913164ccba75bb3438cba2f12abb0508634c41254798ed2b0b8b4acfb50af6b022d5fcec555c2b75b090c0aec221710691c63

test:
  secret_key_base: 846fd99b71ae832e0450cb75770f8a568523ad4b99e06f17c681ef3bce87dcd8cffaf8e31acfaa5905642cc12a4554c5e386d108c4b8848261eaabb5f4c2aeb5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
